/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import ux.ConexionBD;

/**
 *
 * @author Martinez
 */
public class frmCrearCuenta extends javax.swing.JFrame {
    private String idClienteEnSesion;

    /**
     * Creates new form frmCrearCuenta
     */
    public frmCrearCuenta(String id) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.idClienteEnSesion = id;
        
        LocalDate currentDate = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String fechaForm = currentDate.format(formatter);
        
        txtFechaApertura.setText(fechaForm);
        txtIdCliente.setText(String.valueOf(idClienteEnSesion));
        txtFechaApertura.setEnabled(false);
        txtIdCliente.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFechaApertura = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        txtIdCliente = new javax.swing.JTextField();
        imgCancelar = new javax.swing.JLabel();
        imgAceptar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtFechaApertura.setBackground(new java.awt.Color(0, 51, 51));
        txtFechaApertura.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaApertura.setText("Fecha de Apertura");

        txtSaldo.setBackground(new java.awt.Color(0, 51, 51));
        txtSaldo.setForeground(new java.awt.Color(255, 255, 255));
        txtSaldo.setText("Saldo");

        txtIdCliente.setBackground(new java.awt.Color(0, 51, 51));
        txtIdCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtIdCliente.setText("ID de Cliente");

        imgCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        imgCancelar.setText("Cancelar");
        imgCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgCancelarMouseClicked(evt);
            }
        });

        imgAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar.png"))); // NOI18N
        imgAceptar.setText("Aceptar");
        imgAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgAceptarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imgCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgAceptar))
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSaldo)
                    .addComponent(txtFechaApertura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFechaApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imgCancelar)
                    .addComponent(imgAceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgCancelarMouseClicked
        // TODO add your handling code here:
        this.dispose();
        frmMenuPrincipal menuPrincipal = new frmMenuPrincipal(idClienteEnSesion);
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_imgCancelarMouseClicked

    private void imgAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgAceptarMouseClicked
        // TODO add your handling code here:
        String fechaApertura = txtFechaApertura.getText();
        double saldo = Double.parseDouble(txtSaldo.getText());
        int id = Integer.parseInt(txtIdCliente.getText());
        
        try{
            Connection conexion = ConexionBD.openConnection();
            String consulta = "INSERT INTO Cuentas (fechaApertura, saldo, id) VALUES (?,?,?)";
            PreparedStatement pstm = conexion.prepareStatement(consulta, Statement.RETURN_GENERATED_KEYS);
            pstm.setString(1, fechaApertura);
            pstm.setDouble(2, saldo);
            pstm.setInt(3, id);
            
            int filasInsertadas = pstm.executeUpdate();
            
            if(filasInsertadas > 0){
                ResultSet genKeys = pstm.getGeneratedKeys();
                if(genKeys.next()){
                    int idCuenta = genKeys.getInt(1);
                    JOptionPane.showMessageDialog(this, "El ID de su cuenta es: " + idCuenta);
                }
                this.dispose();
                frmMenuPrincipal menuPrincipal = new frmMenuPrincipal(idClienteEnSesion);
                menuPrincipal.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "Error.");
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error de conexion o consulta. " + e.getMessage());
        }
    }//GEN-LAST:event_imgAceptarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgAceptar;
    private javax.swing.JLabel imgCancelar;
    private javax.swing.JTextField txtFechaApertura;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
