/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import ux.ConexionBD;
import ux.Conversiones;

/**
 *
 * @author Martinez
 */
public class frmRetiroCuentaPropia extends javax.swing.JFrame {
    private String idClienteEnSesion;
    /**
     * Creates new form frmRetiroCuentaPropia
     */
    public frmRetiroCuentaPropia(String id) {
        initComponents();
        setLocationRelativeTo(null);
        
        imgCancelar.requestFocusInWindow();
        this.idClienteEnSesion = id;
        cargarCuentasCliente();
        
        // Agregar un FocusListener
        txtMonto.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (txtMonto.getText().equals("Monto")) {
                    txtMonto.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (txtMonto.getText().isEmpty()) {
                    txtMonto.setText("Monto");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMove1 = new javax.swing.JPanel();
        imgCerrar1 = new javax.swing.JLabel();
        imgMinimizar = new javax.swing.JLabel();
        cmbCuentas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        imgCancelar = new javax.swing.JLabel();
        imgAceptar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlMove1.setBackground(new java.awt.Color(0, 51, 51));

        imgCerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        imgCerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgCerrar1MouseClicked(evt);
            }
        });

        imgMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimizar.png"))); // NOI18N
        imgMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgMinimizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlMove1Layout = new javax.swing.GroupLayout(pnlMove1);
        pnlMove1.setLayout(pnlMove1Layout);
        pnlMove1Layout.setHorizontalGroup(
            pnlMove1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMove1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(imgMinimizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgCerrar1))
        );
        pnlMove1Layout.setVerticalGroup(
            pnlMove1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgCerrar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(imgMinimizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cmbCuentas.setBackground(new java.awt.Color(0, 51, 51));
        cmbCuentas.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        cmbCuentas.setForeground(new java.awt.Color(255, 255, 255));
        cmbCuentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("Cuenta de Origen:");

        txtMonto.setBackground(new java.awt.Color(0, 51, 51));
        txtMonto.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(255, 255, 255));
        txtMonto.setText("Monto");

        imgCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        imgCancelar.setText("Cancelar");
        imgCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgCancelarMouseClicked(evt);
            }
        });

        imgAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar.png"))); // NOI18N
        imgAceptar.setText("Aceptar");
        imgAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgAceptarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMove1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(cmbCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imgCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgAceptar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlMove1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imgCancelar)
                    .addComponent(imgAceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgCerrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgCerrar1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        frmMenuPrincipal menuPrincipal = new frmMenuPrincipal(idClienteEnSesion);
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_imgCerrar1MouseClicked

    private void imgMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgMinimizarMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_imgMinimizarMouseClicked

    private void imgCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgCancelarMouseClicked
        // TODO add your handling code here:
        this.dispose();
        frmMenuPrincipal menuPrincipal = new frmMenuPrincipal(idClienteEnSesion);
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_imgCancelarMouseClicked

    private void imgAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgAceptarMouseClicked
        // TODO add your handling code here:
        String cuentaOrigen = cmbCuentas.getSelectedItem().toString();
        double monto = Double.parseDouble(txtMonto.getText());
        realizarRetiro(cuentaOrigen, monto);
    }//GEN-LAST:event_imgAceptarMouseClicked

    private void cargarCuentasCliente(){
        cmbCuentas.removeAllItems();
        Conversiones conversiones = new Conversiones();
        List<List<Object>> cuentasCliente = conversiones.obtenerCuentasCliente(idClienteEnSesion);
        
        for(List<Object> cuenta : cuentasCliente){
            String numeroCuenta = cuenta.get(0).toString();
            cmbCuentas.addItem(numeroCuenta);
        }
    }

    private void realizarRetiro(String cuentaOrigen, double monto) {
        try {
            Connection conexion = ConexionBD.openConnection();
            
            // Obtener el saldo actual
            double saldoActual = 0;
            String consultaSaldo = "SELECT saldo FROM Cuentas WHERE numeroCuenta = ?";
            PreparedStatement pstmSaldo = conexion.prepareStatement(consultaSaldo);
            pstmSaldo.setString(1, cuentaOrigen);
            ResultSet rsSaldo = pstmSaldo.executeQuery();
            if (rsSaldo.next()) {
                saldoActual = rsSaldo.getDouble("saldo");
            } else {
                JOptionPane.showMessageDialog(null, "No se encontro la cuenta.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Verificar si hay suficiente saldo para realizar el retiro
            if (saldoActual < monto) {
                JOptionPane.showMessageDialog(null, "Saldo insuficiente en la cuenta.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Calcular el nuevo saldo después del retiro
            double nuevoSaldo = saldoActual - monto;
            
            // Actualizar el saldo
            String consultaActualizar = "UPDATE Cuentas SET saldo = ? WHERE numeroCuenta = ?";
            PreparedStatement pstmActualizar = conexion.prepareStatement(consultaActualizar);
            pstmActualizar.setDouble(1, nuevoSaldo);
            pstmActualizar.setString(2, cuentaOrigen);
            int filasActualizadas = pstmActualizar.executeUpdate();
            
            if (filasActualizadas > 0) {
                JOptionPane.showMessageDialog(null, "Retiro realizado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                
                // Obtener la fecha actual
                java.util.Date fechaActual = new java.util.Date();
                java.sql.Date fechaSQL = new java.sql.Date(fechaActual.getTime());
                
                // Insertar en la tabla Operaciones
                String consultaOperacion = "INSERT INTO Operaciones (fechaOperacion, tipoOperacion, cuentaOrigen, monto, id, numeroCuenta) VALUES (?, ?, ?, ?, ?, ?)";
                PreparedStatement pstmOperacion = conexion.prepareStatement(consultaOperacion);
                pstmOperacion.setDate(1, fechaSQL);
                pstmOperacion.setString(2, "RetiroCP");
                pstmOperacion.setString(3, cuentaOrigen);
                pstmOperacion.setDouble(4, monto);
                pstmOperacion.setString(5, idClienteEnSesion);
                pstmOperacion.setString(6, cuentaOrigen);
                pstmOperacion.executeUpdate();
            } 
            else {
                JOptionPane.showMessageDialog(null, "Error al realizar el retiro.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            conexion.close();
        } catch 
        (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al realizar el retiro. " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCuentas;
    private javax.swing.JLabel imgAceptar;
    private javax.swing.JLabel imgCancelar;
    private javax.swing.JLabel imgCerrar1;
    private javax.swing.JLabel imgMinimizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlMove1;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
